pipeline {
  agent any

  stages {
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t my-python-app -f calculator_proj/Dockerfile .'
      }
    }

    stage('Run Tests') {
      steps {
        sh 'docker run --rm my-python-app'
      }
    }
  }
}
