pipeline {
  agent any

  stages {
    stage('Build Docker Image') {
      steps {
        // Build Docker image using calculator_proj as context (Dockerfile inside it)
        sh 'docker build -t my-python-app calculator_proj/'
      }
    }

    stage('Run Tests') {
      steps {
        sh 'docker run --rm my-python-app'
      }
    }
  }
}
